stages:
    - build
    - lint

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
        - if: $CI_COMMIT_BRANCH == 'master'

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/

default:
    before_script:
        - node -v
        - npm -v
        - npm install --ignore-scripts

build:
    stage: build
    image: gitlab.robingenz.de:4567/robingenz/docker-node-opencv/node-opencv:latest
    tags:
        - docker
    script:
        - npm run build

lint:
    stage: lint
    image: gitlab.robingenz.de:4567/robingenz/docker-node-opencv/node-opencv:latest
    tags:
        - docker
    script:
        - npm run lint
